"""model

Revision ID: 9c468d366f19
Revises: 
Create Date: 2024-03-02 20:14:23.348812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c468d366f19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('datasets_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_list_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_datasets_list_user_id'), ['user_id'], unique=False)

    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=150), nullable=False),
    sa.Column('answer', sa.String(length=30), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Float(), nullable=False),
    sa.Column('lst_apperance', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_answer'), ['answer'], unique=True)
        batch_op.create_index(batch_op.f('ix_dataset_correct'), ['correct'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_factor'), ['factor'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_lst_apperance'), ['lst_apperance'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_question'), ['question'], unique=True)
        batch_op.create_index(batch_op.f('ix_dataset_wrong'), ['wrong'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_wrong'))
        batch_op.drop_index(batch_op.f('ix_dataset_question'))
        batch_op.drop_index(batch_op.f('ix_dataset_lst_apperance'))
        batch_op.drop_index(batch_op.f('ix_dataset_factor'))
        batch_op.drop_index(batch_op.f('ix_dataset_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_correct'))
        batch_op.drop_index(batch_op.f('ix_dataset_answer'))

    op.drop_table('dataset')
    with op.batch_alter_table('datasets_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_list_user_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_list_name'))

    op.drop_table('datasets_list')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
