"""changes

Revision ID: bef09513adf0
Revises: c96bc719829e
Create Date: 2024-03-04 11:27:37.327541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef09513adf0'
down_revision = 'c96bc719829e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lst_appearance', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_pair_lst_apperance')
        batch_op.create_index(batch_op.f('ix_pair_lst_appearance'), ['lst_appearance'], unique=False)
        batch_op.drop_column('lst_apperance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lst_apperance', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_pair_lst_appearance'))
        batch_op.create_index('ix_pair_lst_apperance', ['lst_apperance'], unique=False)
        batch_op.drop_column('lst_appearance')

    # ### end Alembic commands ###
