"""structure changes

Revision ID: c96bc719829e
Revises: 9c468d366f19
Create Date: 2024-03-03 19:40:55.882525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96bc719829e'
down_revision = '9c468d366f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_info_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_dataset_info_user_id'), ['user_id'], unique=False)

    op.create_table('pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=150), nullable=False),
    sa.Column('answer', sa.String(length=30), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Float(), nullable=False),
    sa.Column('lst_apperance', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pair', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pair_answer'), ['answer'], unique=True)
        batch_op.create_index(batch_op.f('ix_pair_correct'), ['correct'], unique=False)
        batch_op.create_index(batch_op.f('ix_pair_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pair_factor'), ['factor'], unique=False)
        batch_op.create_index(batch_op.f('ix_pair_lst_apperance'), ['lst_apperance'], unique=False)
        batch_op.create_index(batch_op.f('ix_pair_question'), ['question'], unique=True)
        batch_op.create_index(batch_op.f('ix_pair_wrong'), ['wrong'], unique=False)

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index('ix_dataset_answer')
        batch_op.drop_index('ix_dataset_correct')
        batch_op.drop_index('ix_dataset_dataset_id')
        batch_op.drop_index('ix_dataset_factor')
        batch_op.drop_index('ix_dataset_lst_apperance')
        batch_op.drop_index('ix_dataset_question')
        batch_op.drop_index('ix_dataset_wrong')

    op.drop_table('dataset')
    with op.batch_alter_table('datasets_list', schema=None) as batch_op:
        batch_op.drop_index('ix_datasets_list_name')
        batch_op.drop_index('ix_datasets_list_user_id')

    op.drop_table('datasets_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets_list', schema=None) as batch_op:
        batch_op.create_index('ix_datasets_list_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_datasets_list_name', ['name'], unique=1)

    op.create_table('dataset',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=150), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=30), nullable=False),
    sa.Column('factor', sa.FLOAT(), nullable=False),
    sa.Column('correct', sa.INTEGER(), nullable=False),
    sa.Column('wrong', sa.FLOAT(), nullable=False),
    sa.Column('lst_apperance', sa.INTEGER(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index('ix_dataset_wrong', ['wrong'], unique=False)
        batch_op.create_index('ix_dataset_question', ['question'], unique=1)
        batch_op.create_index('ix_dataset_lst_apperance', ['lst_apperance'], unique=False)
        batch_op.create_index('ix_dataset_factor', ['factor'], unique=False)
        batch_op.create_index('ix_dataset_dataset_id', ['dataset_id'], unique=False)
        batch_op.create_index('ix_dataset_correct', ['correct'], unique=False)
        batch_op.create_index('ix_dataset_answer', ['answer'], unique=1)

    with op.batch_alter_table('pair', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pair_wrong'))
        batch_op.drop_index(batch_op.f('ix_pair_question'))
        batch_op.drop_index(batch_op.f('ix_pair_lst_apperance'))
        batch_op.drop_index(batch_op.f('ix_pair_factor'))
        batch_op.drop_index(batch_op.f('ix_pair_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_pair_correct'))
        batch_op.drop_index(batch_op.f('ix_pair_answer'))

    op.drop_table('pair')
    with op.batch_alter_table('dataset_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_info_user_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_info_name'))

    op.drop_table('dataset_info')
    # ### end Alembic commands ###
